# Generated by Django 4.0 on 2021-12-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Clientname')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Client email')),
                ('client_message', models.TimeField()),
                ('client_message_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=100, verbose_name='Username')),
                ('message_email', models.EmailField(max_length=254, verbose_name='User email')),
                ('message_content', models.TimeField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
