# Generated by Django 4.0 on 2021-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(max_length=300),
        ),
    ]
