# Generated by Django 4.0 on 2021-12-26 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_booking_client_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
