# Generated by Django 4.0 on 2021-12-26 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_message_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_phoneNumber',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
