# Generated by Django 4.0 on 2021-12-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_booking_client_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_pic', models.ImageField(upload_to='pics')),
                ('hero_caption', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=80)),
            ],
        ),
    ]
