# Generated by Django 4.0 on 2021-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='banner',
            field=models.ImageField(default=1, upload_to='media/pics'),
            preserve_default=False,
        ),
    ]
