# Generated by Django 4.0 on 2021-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_about_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(upload_to='media/pics')),
                ('caption', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
