# Generated by Django 4.0 on 2022-01-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='pics',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=1, upload_to='media/pics'),
            preserve_default=False,
        ),
    ]
