# Generated by Django 4.0 on 2022-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_pics_service_banner_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=10)),
            ],
        ),
    ]
