# Generated by Django 4.0 on 2022-01-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_testimony_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='job',
            field=models.CharField(max_length=20),
        ),
    ]
