# Generated by Django 4.0 on 2022-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_testimony_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='media/pics')),
                ('topic', models.CharField(max_length=80)),
                ('content', models.TextField(max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
