# Generated by Django 4.0 on 2022-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('gmail', models.CharField(max_length=300)),
                ('phone1', models.CharField(max_length=17)),
                ('phone2', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleMap', models.URLField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SocailMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=1000)),
                ('instagram', models.URLField(max_length=1000)),
                ('twitter', models.URLField(max_length=1000)),
                ('whatsapp', models.URLField(max_length=1000)),
            ],
        ),
    ]
