# Generated by Django 4.0 on 2022-01-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_contact_map_socailmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='SocailMedia',
        ),
    ]
