# Generated by Django 4.0 on 2022-01-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_address_remove_contact_city_remove_contact_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=10000)),
                ('instagram', models.URLField(max_length=10000)),
                ('twitter', models.URLField(max_length=10000)),
                ('whatsapp', models.URLField(max_length=10000)),
            ],
        ),
    ]
