# Generated by Django 4.0 on 2022-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='facebook',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='instagram',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='twitter',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='whatsapp',
            field=models.URLField(max_length=1000),
        ),
    ]
